# tasks file
---
- name: certificates | create files directories
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
    owner: "{{ item.owner | default(nginx_default_owner) }}"
    group: "{{ item.group | default(nginx_default_group) }}"
    mode: 0750
  with_items: "{{ nginx_ssl_map }}"
  tags:
    - nginx-certificates-directories

- name: certificates | copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(nginx_default_owner) }}"
    group: "{{ item.group | default(nginx_default_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  with_items: "{{ nginx_ssl_map }}"
  notify: restart nginx
  tags:
    - nginx-certificates-copy
