# tasks file for nginx
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ nginx_dependencies }}"
  tags:
    - nginx-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ nginx_install }}"
  tags:
    - nginx-install-additional
