# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ nginx_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - nginx-install-dependencies

- name: install | additional
  apt:
    name: "{{ nginx_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - nginx-install-additional
