# tasks file
---
- name: check version support
  ansible.builtin.fail:
    msg: "NGINX version {{ nginx_version }} is not supported"
  when: nginx_version not in nginx_versions_supported
  tags:
    - configuration
    - nginx
    - nginx-check-version-support

- name: repository
  ansible.builtin.import_tasks: repository.yml
  when: nginx_use_ppa | bool
  tags:
    - configuration
    - nginx
    - nginx-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - nginx
    - nginx-install

- name: certificates
  ansible.builtin.import_tasks: certificates.yml
  tags:
    - configuration
    - nginx
    - nginx-certificates

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - nginx
    - nginx-configure

- name: start and enable service
  ansible.builtin.service:
    name: nginx
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - nginx
    - nginx-start-enable-service
