# tasks file for nginx
---
- name: repository | add public key
  apt_key:
    id: ABF5BD827BD9BF62
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  when: nginx_use_ppa
  tags:
    - nginx-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ nginx_repositories }}"
  when: nginx_use_ppa | bool
  tags:
    - nginx-repository-add
