# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ nginx_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - nginx-repository-install-dependencies

- name: repository | (keyrings) directory | create
  ansible.builtin.file:
    path: "{{ nginx_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - nginx-repository-keyrings-directory-create

- name: repository | (keyring) file | download  # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: >
    wget -O- {{ nginx_keyring_src }} | gpg --dearmor --yes --output {{ nginx_keyring_dst }}
  args:
    creates: "{{ nginx_keyring_dst }}"
  tags:
    - nginx-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    mode: '0644'
  with_items: "{{ nginx_repositories }}"
  tags:
    - nginx-repository-add

- name: repository | apt-pin packages
  ansible.builtin.copy:
    src: etc/apt/preferences.d/00nginx.pref
    dest: /etc/apt/preferences.d/00nginx.pref
    owner: root
    group: root
    mode: '0644'
  tags:
    - nginx-repository-apt-pin
