# tasks file
---
- name: repository | install | dependencies (pre)
  ansible.builtin.apt:
    name: "{{ nginx_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - nginx-repository-install
    - nginx-repository-install-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: ABF5BD827BD9BF62
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  when: nginx_use_ppa | bool
  tags:
    - nginx-repository-public-key

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ nginx_repositories }}"
  when: nginx_use_ppa | bool
  tags:
    - nginx-repository-add
