# handlers file
---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: service_default_state | default('started') == 'started'
