# handlers file for nginx
---
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: service_default_state | default('started') == 'started'
